# Original script from totoa553/OpenTaiko and DragonRatTiger/OpenTaiko

name: Build OpenTaiko

on: 
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Observe the Directory
        shell: cmd
        run: |
          dir

      - name: Build for Windows x64
        shell: cmd
        run: |
          build-win-x64.bat
          
      - name: Create Archive (Win x64)
        shell: cmd
        run: |
          cd OpenTaiko\bin\Release\net7.0\win-x64\
          7z a ../../../../../OpenTaiko.Win.x64.zip publish/ -xr!publish/Songs/ -xr!publish/FFmpeg/ -xr!publish/System/
          7z u ../../../../../OpenTaiko.Win.x64.zip "publish/FFmpeg/win-x64/*" "publish/Songs/L2 Custom Charts/*" "publish/Songs/L3 Downloaded Songs/*" "publish/Songs/S1 Dan-i Dojo/box.def" "publish/Songs/S2 Taiko Towers/box.def" "publish/Songs/X1 Favorite/*" "publish/Songs/X2 Recent/*" "publish/Songs/X3 Search By Difficulty/*"
          cd ..\..\..\..\..\
          
      - name: Build for Mac x64
        shell: cmd
        run: |
          build-osx-x64.bat
          
      - name: Create Archive (Mac x64)
        shell: cmd
        run: |
          cd OpenTaiko\bin\Release\net7.0\osx-x64\
          7z a ../../../../../OpenTaiko.Mac.x64.zip publish/ -xr!publish/Songs/ -xr!publish/FFmpeg/ -xr!publish/System/
          7z u ../../../../../OpenTaiko.Mac.x64.zip "publish/FFmpeg/osx-x64/*" "publish/Songs/L2 Custom Charts/*" "publish/Songs/L3 Downloaded Songs/*" "publish/Songs/S1 Dan-i Dojo/box.def" "publish/Songs/S2 Taiko Towers/box.def" "publish/Songs/X1 Favorite/*" "publish/Songs/X2 Recent/*" "publish/Songs/X3 Search By Difficulty/*"
          cd ..\..\..\..\..\
      
      - name: Build for Linux x64
        shell: cmd
        run: |
          build-linux-x64.bat
          
      - name: Create Archive (Linux x64)
        shell: cmd
        run: |
          cd OpenTaiko\bin\Release\net7.0\linux-x64\
          7z a ../../../../../OpenTaiko.Linux.x64.zip publish/ -xr!publish/Songs/ -xr!publish/FFmpeg/ -xr!publish/System/
          7z u ../../../../../OpenTaiko.Linux.x64.zip "publish/FFmpeg/linux-x64/*" "publish/Songs/L2 Custom Charts/*" "publish/Songs/L3 Downloaded Songs/*" "publish/Songs/S1 Dan-i Dojo/box.def" "publish/Songs/S2 Taiko Towers/box.def" "publish/Songs/X1 Favorite/*" "publish/Songs/X2 Recent/*" "publish/Songs/X3 Search By Difficulty/*"
          cd ..\..\..\..\..\
          
      - uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: OpenTaiko/OpenTaiko.csproj

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: "${{steps.get-version.outputs.version}}"

      - name: Create Release
        if: steps.check-tag.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: "${{steps.get-version.outputs.version}}"
          release_name: OpenTaiko v${{steps.get-version.outputs.version}}
          draft: false
          prerelease: false
     
      - name: Upload All Builds
        uses: xresloader/upload-to-github-release@v1.4.2
        with:
          file: "OpenTaiko.Win.x64.zip;OpenTaiko.Mac.x64.zip;OpenTaiko.Linux.x64.zip"
          overwrite: true
          tag_name: "${{steps.get-version.outputs.version}}"
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}